default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: jawsapi_development

test: &test
  <<: *default
  database: jawsapi_test

production:
  <<: *default
  database: jawsapi_production
  username: jaws
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
